root: true
parser: "@typescript-eslint/parser"
extends:
  - "airbnb-typescript"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/typescript"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
  - "prettier/react"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: "./tsconfig.json"
settings:
  react:
    version: detect
rules:
  "jest/no-disabled-tests": "warn"
  "jest/no-focused-tests": "error"
  "jest/no-identical-title": "error"
  "jest/prefer-to-have-length": "warn"
  "jest/valid-expect": "error"
  "react/jsx-filename-extension":
    - error
    - extensions:
        - ".jsx"
        - ".tsx"
env:
  browser: true
